FROM python:3.10.12

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    dos2unix \
    && apt-get clean

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . /app/

RUN dos2unix backend_c.sh && chmod +x backend_c.sh

EXPOSE 8000

ENTRYPOINT ["bash", "backend_c.sh"]
